"use client";
import { motion } from "framer-motion";

export default function Hero() {
  return (
      <section className="relative flex flex-col items-center justify-center min-h-screen px-6 text-center overflow-hidden">
            {/* Background Media Overlay */}
                  <div className="absolute inset-0 z-0">
                          <video
                                    autoPlay
                                              loop
                                                        muted
                                                                  playsInline
                                                                            className="w-full h-full object-cover opacity-40"
                                                                                    >
                                                                                                        <source 
                                                                                                                    src="https://peach-elderly-meadowlark-381.mypinata.cloud/ipfs/bafybeigulvyvggr56ldq47jagdkcysdz5nghddey6revr2g6obgijvh3q4/sunny.gif" 
                                                                                                                                type="video/mp4" 
                                                                                                                                          />
                                                                                                                                                    {/* Fallback for the GIF sitting */}
                                                                                                                                                              <source src="/hero.bg.mp4" type="video/mp4" />
                                                                                                                                                                      </video>
                                                                                                                                                                              
                                                                                                                                                                                              <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#050505]/60 to-[#050505]"></div>
                                                                                                                                                                                                    </div>

                                                                                                                                                                                                          {/* Content */}
                                                                                                                                                                                                                <motion.div
                                                                                                                                                                                                                        initial={{ opacity: 0, y: 20 }}
                                                                                                                                                                                                                                animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                        transition={{ duration: 1 }}
                                                                                                                                                                                                                                                className="relative z-10" 
                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                              <h1 className="text-6xl md:text-8xl font-bold mb-6 italic tracking-tight text-white">
                                                                                                                                                                                                                                                                        Zee's World
                                                                                                                                                                                                                                                                                </h1>
                                                                                                                                                                                                                                                                                        <p className="max-w-xl mx-auto text-lg md:text-xl text-gray-200 leading-relaxed mb-10 drop-shadow-lg">
                                                                                                                                                                                                                                                                                                  A digital attic where I keep my 
                                                                                                                                                                                                                                                                                                            <span className="text-purple-400 font-bold"> full-stack experiments</span>, 
                                                                                                                                                                                                                                                                                                                      <span className="text-blue-400 font-bold"> Web3 rabbit holes</span>, and 
                                                                                                                                                                                                                                                                                                                                <span className="text-pink-400 font-bold"> AI-generated fever dreams</span>.
                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                <div className="flex gap-6 justify-center">
                                                                                                                                                                                                                                                                                                                                                          <button className="px-10 py-3 bg-white text-black rounded-full hover:scale-105 transition-transform font-bold shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                      View Work
                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                          <button className="px-10 py-3 border border-white/40 bg-black/20 backdrop-blur-md text-white rounded-full hover:bg-white/10 transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                      <a 
                                                                                                                                                                                                                                                                                                                                                                                                        href="https://zeesworld01.substack.com" 
                                                                                                                                                                                                                                                                                                                                                                                                          target="_blank" 
                                                                                                                                                                                                                                                                                                                                                                                                            rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                              className="px-10 py-3 border border-white/40 bg-black/20 backdrop-blur-md text-white rounded-full hover:bg-white/10 transition-colors inline-block"
                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                Substack
                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
