"use client";
import { motion } from "framer-motion";

const projects = [
  {
      title: "Somnia Orchestra",
          logo: "https://gateway.pinata.cloud/ipfs/QmYourCidForBlockPartyLogo", // Image 3 fits this vibe
              description: "Turning the blockchain into a symphony. I decided transaction hashes were too boring, so I mapped real-time activity to musical notes and visual orbs. A stress test for your ears and your GPU.",
                  video: "https://youtube.com/your-video-link", 
                      link: "https://somnia-project.com",
                          tech: ["Ethers.js", "Tone.js", "React"],
                              status: "Functional Chaos"
                                },
                                  {
                                      title: "ZEIROKO",
                                          logo: "https://gateway.pinata.cloud/ipfs/QmYourCidForZeirokoLogo", 
                                              description: "Mission control for social media chaos. A high-performance dashboard for hosts to manage panels and guest lists without losing their minds. Built because manual tracking is for people with too much free time.",
                                                  video: "https://youtube.com/zeiroko-demo",
                                                      link: "https://zeiroko.com",
                                                          tech: ["Next.js", "Supabase", "Tailwind"],
                                                              status: "MVP (Mostly Vibrant)"
                                                                },
                                                                  {
                                                                      title: "The AI OS",
                                                                          logo: "https://gateway.pinata.cloud/ipfs/QmYourCidForOracleGambitLogo",
                                                                              description: "Giving my workspace a brain. An all-in-one hub that generates agendas and transcribes audio in real-time, basically like having a very smart intern who never sleeps and doesn’t ask for a salary." ,
                                                                                  video: "#", 
                                                                                      link: "#",
                                                                                          tech: ["OpenAI API", "Audio Processing", "Next.js"],
                                                                                              status: "Half-Finished Genius"
                                                                                                },
                                                                                                  {
                                                                                                      title: "OneTransfer Roulette",
                                                                                                          logo: "https://gateway.pinata.cloud/ipfs/QmYourCidForGenericLogo", 
                                                                                                              description: "Financial transactions, but make it a game. A payment application built on OneChain that adds a layer of gamification to transfers. Because why should sending money be predictable?",
                                                                                                                  video: "#", 
                                                                                                                      link: "#",
                                                                                                                          tech: ["OneChain", "Solidity"],
                                                                                                                              status: "Experimental/Half-Baked"
                                                                                                                                },
                                                                                                                                  {
                                                                                                                                      title: "Mirror",
                                                                                                                                          logo: "https://gateway.pinata.cloud/ipfs/QmYourCidForZeeWorldLogo", // Using Image 1 for your cinematic brand
                                                                                                                                              description: "13 seconds of existential AI crisis. A short-form video experiment exploring the interaction between humans and AI. Edited entirely on my phone because I like to suffer.",
                                                                                                                                                  video: "https://your-video-link", 
                                                                                                                                                      link: "#",
                                                                                                                                                          tech: ["Cinematic AI", "VN Editor", "Mobile"],
                                                                                                                                                              status: "Final Cut"
                                                                                                                                                                },
                                                                                                                                                                  {
                                                                                                                                                                      title: "MySky",
                                                                                                                                                                          logo: "https://gateway.pinata.cloud/ipfs/QmYourCidForWeatherLogo", 
                                                                                                                                                                              description: "Legacy R&D: A dynamic NFT that shifted visual states based on the holder's physical local weather via Zapier oracles. My first deep dive into real-world data reactivity.",
                                                                                                                                                                                  video: "#", 
                                                                                                                                                                                      link: "https://mysky.page.gd/?i=1",
                                                                                                                                                                                          tech: ["Solidity", "Zapier", "Oracles"],
                                                                                                                                                                                              status: "Retired Prototype"
                                                                                                                                                                                                }
                                                                                                                                                                                                ];

                                                                                                                                                                                                export default function ProjectGallery() {
                                                                                                                                                                                                  return (
                                                                                                                                                                                                      <section id="projects" className="py-20 px-6 max-w-7xl mx-auto">
                                                                                                                                                                                                            <div className="text-center mb-16">
                                                                                                                                                                                                                    <h2 className="text-4xl font-bold italic text-[#a855f7]">The Vault</h2>
                                                                                                                                                                                                                            <p className="text-xs text-gray-500 mt-2 uppercase tracking-[0.2em]">Restricted Access | Project Logs v2.0</p>
                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                                                                                                                                                                                                                                                {projects.map((project, i) => (
                                                                                                                                                                                                                                                          <motion.div 
                                                                                                                                                                                                                                                                      key={i} 
                                                                                                                                                                                                                                                                                  initial={{ opacity: 0, y: 30 }}
                                                                                                                                                                                                                                                                                              whileInView={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                          viewport={{ once: true }}
                                                                                                                                                                                                                                                                                                                      whileHover={{ y: -5 }}
                                                                                                                                                                                                                                                                                                                                  className="group relative p-px bg-gradient-to-b from-white/10 to-transparent rounded-[2.5rem] overflow-hidden"
                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                        <div className="bg-[#0f071a]/95 backdrop-blur-xl p-8 h-full rounded-[2.4rem] flex flex-col border border-white/5">
                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between items-start mb-6">
                                                                                                                                                                                                                                                                                                                                                                                      <div className="w-14 h-14 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                         <img 
                                                                                                                                                                                                                                                                                                                              src={project.logo} 
                                                                                                                                                                                                                                                                                                                                   alt={project.title} 
                                                                                                                                                                                                                                                                                                                                                        className="w-full h-full object-cover"
                                                                                                                                                                                                                                                                                                                                                                             onError={(e) => { (e.target as HTMLImageElement).style.display = 'none' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href={project.video} className="text-[10px] font-bold uppercase tracking-widest text-blue-400 hover:text-blue-300">Demo</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href={project.link} className="text-[10px] font-bold uppercase tracking-widest text-purple-400 hover:text-purple-300">Link</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-xl font-bold text-white mb-3 italic tracking-tight">{project.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[#cdc4ff]/70 text-sm leading-relaxed mb-8 flex-grow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {project.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-auto space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex flex-wrap gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {project.tech.map(t => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span key={t} className="px-3 py-1 bg-purple-500/10 border border-purple-500/20 rounded-full text-[9px] uppercase tracking-tighter text-purple-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {t}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-2 pt-2 border-t border-white/5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className={`w-1.5 h-1.5 rounded-full ${project.status === 'Live' || project.status === 'Final Cut' ? 'bg-green-500' : 'bg-purple-500 animate-pulse'}`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-[9px] font-bold uppercase tracking-widest text-gray-500">{project.status}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }