"use client";
import { motion } from "framer-motion";

const projects = [
  {
      title: "Somnia Orchestra",
          logo: "/logos/somnia.png",
              description: "Mapping real-time blockchain transactions to musical notes.",
                  video: "https://youtube.com/your-video-link", 
                      link: "https://somnia-project.com",
                          tech: ["Solana", "Tone.js"],
                            },
                              {
                                  title: "ZEIROKO",
                                      logo: "/logos/zeiroko.png",
                                          description: "Space Host Toolkit with session timers and research panels.",
                                              video: "https://youtube.com/zeiroko-demo",
                                                  link: "https://zeiroko.com",
                                                      tech: ["Next.js", "Supabase"],
                                                        }
                                                        ];

                                                        export default function ProjectGallery() {
                                                          return (
                                                              <section className="py-20 px-6 max-w-6xl mx-auto">
                                                                    <h2 className="text-4xl font-bold mb-12 italic text-center text-[#a855f7]">The Vault</h2>
                                                                          <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                                                                                  {projects.map((project, i) => (
                                                                                            <motion.div 
                                                                                                        key={i}
                                                                                                                    initial={{ opacity: 0, y: 30 }}
                                                                                                                                whileInView={{ opacity: 1, y: 0 }}
                                                                                                                                            whileHover={{ scale: 1.02, rotate: 1 }}
                                                                                                                                                        className="p-1 bg-gradient-to-br from-purple-500/20 to-blue-500/20 rounded-3xl backdrop-blur-xl border border-white/10 shadow-2xl"
                                                                                                                                                                  >
                                                                                                                                                                              <div className="bg-[#0f071a]/80 rounded-[22px] p-6 h-full">
                                                                                                                                                                                            <div className="flex justify-between items-start mb-4">
                                                                                                                                                                                                            <img src={project.logo} className="w-12 h-12 rounded-lg object-contain bg-white/5 p-1" alt="logo" />
                                                                                                                                                                                                                            <div className="flex gap-3">
                                                                                                                                                                                                                                              <a href={project.video} target="_blank" className="text-xs text-blue-400 hover:underline underline-offset-4">Watch Demo</a>
                                                                                                                                                                                                                                                                <a href={project.link} target="_blank" className="text-xs text-purple-400 hover:underline underline-offset-4">Live Site</a>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                            <h3 className="text-2xl font-bold text-white mb-2">{project.title}</h3>
                                                                                                                                                                                                                                                                                                                          <p className="text-[#cdc4ff] mb-6 line-clamp-2">{project.description}</p>
                                                                                                                                                                                                                                                                                                                                        <div className="flex flex-wrap gap-2">
                                                                                                                                                                                                                                                                                                                                                        {project.tech.map(t => (
                                                                                                                                                                                                                                                                                                                                                                          <span key={t} className="px-3 py-1 bg-purple-500/10 border border-purple-500/20 rounded-full text-[10px] uppercase tracking-widest text-purple-300">
                                                                                                                                                                                                                                                                                                                                                                                              {t}
                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        