"use client";
import { motion } from "framer-motion";

const projects = [
  {
      title: "Somnia Orchestra",
          description: "Mapping real-time blockchain transactions to musical notes and visual orbs.",
              tech: ["Ethers.js", "Tone.js", "Next.js"],
                  video: "/video1.mp4", // Replace with your file names
                    },
                      {
                          title: "ZEIROKO",
                              description: "A high-performance toolkit for social media hosts featuring session timers and research panels.",
                                  tech: ["Next.js", "Supabase", "Tailwind"],
                                      video: "/video2.mp4",
                                        },
                                        ];

                                        export default function ProjectGallery() {
                                          return (
                                              <section id="projects" className="py-20 px-6 bg-transparent">
                                                    <h2 className="text-4xl font-bold mb-12 italic text-center">Featured Work</h2>
                                                          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-6xl mx-auto">
                                                                  {projects.map((project, index) => (
                                                                            <motion.div 
                                                                                        key={index}
                                                                                                    whileHover={{ y: -10 }}
                                                                                                                className="group relative bg-white/5 border border-white/10 rounded-3xl overflow-hidden backdrop-blur-md"
                                                                                                                          >
                                                                                                                                      <div className="aspect-video w-full bg-gray-800 relative">
                                                                                                                                                    <video 
                                                                                                                                                                    src={project.video} 
                                                                                                                                                                                    muted loop playsInline 
                                                                                                                                                                                                    className="w-full h-full object-cover opacity-60 group-hover:opacity-100 transition-opacity"
                                                                                                                                                                                                                    onMouseOver={(e) => e.currentTarget.play()}
                                                                                                                                                                                                                                    onMouseOut={(e) => e.currentTarget.pause()}
                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                          <div className="p-6">
                                                                                                                                                                                                                                                                                        <h3 className="text-2xl font-bold mb-2">{project.title}</h3>
                                                                                                                                                                                                                                                                                                      <p className="text-gray-400 mb-4">{project.description}</p>
                                                                                                                                                                                                                                                                                                                    <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                    {project.tech.map((t) => (
                                                                                                                                                                                                                                                                                                                                                      <span key={t} className="text-xs border border-white/20 px-3 py-1 rounded-full text-gray-300">
                                                                                                                                                                                                                                                                                                                                                                          {t}
                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    