"use client";
import { motion } from "framer-motion";

const skillCategories = [
  {
      title: "Development",
          skills: ["Next.js", "TypeScript", "Solana / Rust", "Python", "Web3 Protocols"],
              color: "from-blue-500 to-cyan-400"
                },
                  {
                      title: "Creative & AI",
                          skills: ["AI Video Gen", "Prompt Arch", "VN Editor", "Kittl", "Vibe Coding"],
                              color: "from-purple-500 to-pink-500"
                                },
                                  {
                                      title: "The Hard-Drive",
                                          skills: ["Advanced Sarcasm", "Fast Learner (v2.0)", "Medical Science", "Mobile Dev Junkie", "Problem Hunting"],
                                              color: "from-green-400 to-emerald-500"
                                                }
                                                ];

                                                export default function Skills() {
                                                  return (
                                                      <section id="skills" className="py-20 px-6 max-w-6xl mx-auto">
                                                            {/* Header with a little flavor */}
                                                                  <div className="text-center mb-16">
                                                                          <h2 className="text-4xl font-bold italic text-[#a855f7]">The Stack</h2>
                                                                                  <p className="text-xs text-gray-500 mt-2 uppercase tracking-[0.2em]">Hardware: Mobile | OS: Caffeine | Status: Optimizing</p>
                                                                                        </div>

                                                                                              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                                                                                                      {skillCategories.map((cat, i) => (
                                                                                                                <motion.div 
                                                                                                                            key={i} 
                                                                                                                                        initial={{ opacity: 0, y: 20 }}
                                                                                                                                                    whileInView={{ opacity: 1, y: 0 }}
                                                                                                                                                                transition={{ delay: i * 0.1 }}
                                                                                                                                                                            className="p-8 bg-white/5 border border-white/10 rounded-[2rem] backdrop-blur-md hover:border-purple-500/30 transition-colors group"
                                                                                                                                                                                      >
                                                                                                                                                                                                  <h3 className={`text-xl font-bold mb-8 bg-gradient-to-r ${cat.color} bg-clip-text text-transparent italic`}>
                                                                                                                                                                                                                {cat.title}
                                                                                                                                                                                                                            </h3>
                                                                                                                                                                                                                                        <div className="flex flex-wrap gap-3">
                                                                                                                                                                                                                                                      {cat.skills.map((skill) => (
                                                                                                                                                                                                                                                                      <motion.span 
                                                                                                                                                                                                                                                                                        key={skill}
                                                                                                                                                                                                                                                                                                          whileHover={{ 
                                                                                                                                                                                                                                                                                                                              scale: 1.05, 
                                                                                                                                                                                                                                                                                                                                                  backgroundColor: "rgba(168, 85, 247, 0.1)",
                                                                                                                                                                                                                                                                                                                                                                      borderColor: "rgba(168, 85, 247, 0.4)" 
                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                          className="px-4 py-2 bg-white/5 border border-white/5 rounded-2xl text-sm text-[#e0d7ff] cursor-default transition-all italic"
                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                            {skill}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    