import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useWorldStore } from '../store/useWorldStore';
import { districtsData } from '../data/projectsData';

export default function ExpressMenu() {
  const { isMenuOpen, toggleMenu, setActiveDistrict } = useWorldStore();

    return (
        <>
              {/* Sticky Quick Toggle Floating Button */}
                    <button
                            onClick={toggleMenu}
                                    className="absolute top-5 right-5 z-50 flex h-12 w-12 items-center justify-center rounded-xl bg-neutral-900/80 border border-neutral-800 backdrop-blur-md active:scale-95 transition-transform text-xl text-purple-400"
                                          >
                                                  {isMenuOpen ? "✕" : "☰"}
                                                        </button>

                                                              {/* Fullscreen Navigation Modal Drawer */}
                                                                    <AnimatePresence>
                                                                            {isMenuOpen && (
                                                                                      <motion.div
                                                                                                  initial={{ opacity: 0, x: "100%" }}
                                                                                                              animate={{ opacity: 1, x: 0 }}
                                                                                                                          exit={{ opacity: 0, x: "100%" }}
                                                                                                                                      transition={{ type: "spring", damping: 25, stiffness: 200 }}
                                                                                                                                                  className="absolute inset-0 z-40 flex flex-col justify-center bg-neutral-950/95 p-8 backdrop-blur-xl border-l border-neutral-900"
                                                                                                                                                            >
                                                                                                                                                                        <p className="text-xs font-mono uppercase tracking-widest text-neutral-500 mb-6">Express Navigation</p>
                                                                                                                                                                                    
                                                                                                                                                                                                <nav className="flex flex-col space-y-4">
                                                                                                                                                                                                              {Object.entries(districtsData).map(([key, value]) => (
                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                key={key}
                                                                                                                                                                                                                                                                  onClick={() => setActiveDistrict(key)}
                                                                                                                                                                                                                                                                                    className="group flex flex-col items-start text-left border-l-2 border-neutral-800 pl-4 hover:border-purple-500 transition-colors"
                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                      <span className="text-xl font-bold tracking-tight text-neutral-200 group-hover:text-purple-400 transition-colors">
                                                                                                                                                                                                                                                                                                                                          {value.name}
                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                              <span className="text-xs text-neutral-500 font-mono mt-0.5">{value.subtitle}</span>
                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                        </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="absolute bottom-8 left-8 text-neutral-600 font-mono text-[10px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ZEE's WORLD CORE // RUNNING FROM MOBILE TERMINAL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        