import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useWorldStore } from '../store/useWorldStore';
import { projects } from '../data/projectsData';

export default function ProjectDrawer() {
  const { activeProjectId, closeProject } = useWorldStore();
    const currentProject = projects.find(p => p.id === activeProjectId);

      return (
          <AnimatePresence>
                {currentProject && (
                        <>
                                  {/* Backdrop Blur Lockout Overlay */}
                                            <motion.div
                                                        initial={{ opacity: 0 }}
                                                                    animate={{ opacity: 0.5 }}
                                                                                exit={{ opacity: 0 }}
                                                                                            onClick={closeProject}
                                                                                                        className="absolute inset-0 z-40 bg-black/60 backdrop-blur-xs"
                                                                                                                  />

                                                                                                                            {/* Core Content Slider Board */}
                                                                                                                                      <motion.div
                                                                                                                                                  initial={{ y: "100%" }}
                                                                                                                                                              animate={{ y: 0 }}
                                                                                                                                                                          exit={{ y: "100%" }}
                                                                                                                                                                                      transition={{ type: "spring", damping: 30, stiffness: 250 }}
                                                                                                                                                                                                  className="absolute bottom-0 left-0 right-0 z-50 max-h-[80vh] overflow-y-auto rounded-t-3xl bg-neutral-900 border-t border-neutral-800 p-6 shadow-2xl font-sans text-neutral-200"
                                                                                                                                                                                                            >
                                                                                                                                                                                                                        {/* Mobile Touch Drag bar visual accent */}
                                                                                                                                                                                                                                    <div className="mx-auto mb-5 h-1.5 w-12 rounded-full bg-neutral-700" onClick={closeProject} />

                                                                                                                                                                                                                                                {/* Heading Context block */}
                                                                                                                                                                                                                                                            <div className="flex items-center space-x-4 mb-4">
                                                                                                                                                                                                                                                                          <div className="text-4xl p-2 bg-neutral-950 rounded-2xl border border-neutral-800 flex items-center justify-center">
                                                                                                                                                                                                                                                                                          {currentProject.logo}
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                      <h2 className="text-xl font-black text-neutral-100">{currentProject.title}</h2>
                                                                                                                                                                                                                                                                                                                                                      <span className="inline-block px-2 py-0.5 mt-1 text-[10px] font-mono rounded bg-purple-950 text-purple-300 border border-purple-800/50 uppercase tracking-wider">
                                                                                                                                                                                                                                                                                                                                                                        District: {currentProject.district} // {currentProject.status}
                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-neutral-300 leading-relaxed text-sm font-medium mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                            {currentProject.shortDesc}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-neutral-400 text-xs leading-relaxed border-l border-neutral-800 pl-3 py-1 mb-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {currentProject.longDesc}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Tech Stack Pills List */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h4 className="text-xs font-mono uppercase text-neutral-500 tracking-wider mb-2">Compiled Tech</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex flex-wrap gap-1.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {currentProject.techStack.map((tech) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span key={tech} className="px-2.5 py-1 text-xs font-mono rounded-md bg-neutral-950 border border-neutral-800 text-neutral-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {tech}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Action Links Buttons Panel */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="grid grid-cols-2 gap-3 pt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href={currentProject.github} target="_blank" rel="noreferrer" className="flex items-center justify-center py-3 px-4 rounded-xl bg-neutral-950 border border-neutral-800 text-sm font-bold tracking-tight text-neutral-200 active:scale-98 transition-transform">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Source Code
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <a href={currentProject.liveLink} target="_blank" rel="noreferrer" className="flex items-center justify-center py-3 px-4 rounded-xl bg-purple-600 text-sm font-bold tracking-tight text-white active:scale-98 transition-transform shadow-lg shadow-purple-900/20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Launch App
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          