import React from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { useWorldStore } from '../store/useWorldStore';
import { districtsData, projects } from '../data/projectsData';

export default function UIOverlay() {
  const { activeDistrict, openProject } = useWorldStore();
    const districtInfo = districtsData[activeDistrict];

      // Filters the core projects list to only display entries matching the active district view
        const currentDistrictProjects = projects.filter(p => p.district === activeDistrict);

          return (
              <div className="absolute inset-0 pointer-events-none z-10 flex flex-col justify-between p-6">
                    
                          {/* Top Section: Active District Identity Subtitle */}
                                <div className="w-full">
                                        <AnimatePresence mode="wait">
                                                  {districtInfo ? (
                                                              <motion.div
                                                                            key={activeDistrict}
                                                                                          initial={{ opacity: 0, y: -10 }}
                                                                                                        animate={{ opacity: 1, y: 0 }}
                                                                                                                      exit={{ opacity: 0, y: -10 }}
                                                                                                                                    className="max-w-[70%]"
                                                                                                                                                >
                                                                                                                                                              <h1 className="text-2xl font-black tracking-tight text-purple-400">{districtInfo.name}</h1>
                                                                                                                                                                            <p className="text-xs font-mono text-neutral-400 mt-0.5">{districtInfo.subtitle}</p>
                                                                                                                                                                                        </motion.div>
                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                              <motion.div key="default-hud" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                                                                                                                                                                                                                            <p className="text-xs font-mono uppercase tracking-widest text-neutral-500">Zee's World // Active Orbit</p>
                                                                                                                                                                                                                                          <p className="text-[10px] text-neutral-600 font-mono">DRAG OR SWIPE SCREEN TO RECONNAISSANCE</p>
                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                        </AnimatePresence>
                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                    {/* Middle Section: Floating Interactive Trigger Cards (Simulating clicking 3D nodes) */}
                                                                                                                                                                                                                                                                                          <div className="w-full flex flex-col items-start space-y-2 pointer-events-auto">
                                                                                                                                                                                                                                                                                                  {activeDistrict && currentDistrictProjects.length > 0 && (
                                                                                                                                                                                                                                                                                                            <div className="w-full max-w-xs p-4 bg-neutral-900/40 border border-neutral-800/60 backdrop-blur-xs rounded-2xl">
                                                                                                                                                                                                                                                                                                                        <p className="text-[10px] font-mono text-neutral-500 uppercase tracking-wider mb-2">Available Nodes</p>
                                                                                                                                                                                                                                                                                                                                    <div className="space-y-1.5">
                                                                                                                                                                                                                                                                                                                                                  {currentDistrictProjects.map((project) => (
                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                    key={project.id}
                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => openProject(project.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full flex items-center space-x-3 p-2 rounded-xl bg-neutral-950/80 border border-neutral-800 text-left text-xs text-neutral-200 active:scale-98 transition-transform"
                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-base">{project.logo}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="truncate font-medium">{project.title}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Bottom Section: Explanatory Subtext Card */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="w-full text-center pb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-[10px] font-mono text-neutral-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            DESIGN MODE: USE TOP-RIGHT ☰ IF THE RADAR VIEW DISORIENTS YOU
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                